name: Docker Build and Push

on:
  push:
    branches:
      - master
      - dev
      - staging

env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

jobs:
  dev:
    name: Build and push dev image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Dev Image
        run: |
          docker build -t $IMAGE_NAME:dev .

      - name: Push Dev Image
        run: |
          docker push $IMAGE_NAME:dev

  staging:
    name: Build and push staging image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Staging Image
        run: |
          docker build -t $IMAGE_NAME:staging .

      - name: Push Staging Image
        run: |
          docker push $IMAGE_NAME:staging

  production:
    name: Build and push production image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Production Image
        run: |
          docker build -t $IMAGE_NAME:production .

      - name: Push Production Image
        run: |
          docker push $IMAGE_NAME:production
